### ISSUE TITLE
3차 QA

### ISSUE THREAD

**Issue by harryjeonn** [harryjeonn/gollabab-ios#160]
## TODO

* [x] 앱 최초 실행 시 스플래시 권한 안내 팝업 표시 후 허용 누르면 위치가 서울 시청으로 잡힌다.
  * viewModel.isPermission의 상태값이 바뀌어서 그런 것 같다.
* [x] 랜덤 결과에서 기기별 패딩값 다름
  * 폰트가 원인 이였음 -> 폰트문제 해결과 함께 해결
* [x] 폰트 사이즈 수정
