### ISSUE TITLE
4차 QA

### ISSUE THREAD

**Issue by harryjeonn** [harryjeonn/gollabab-ios#167]
## TODO

* [x] 카드 스크롤 영역 미쳐날뜀
* [x] 앱 최초실행 광고 제거
* [x] 폰트 사이즈 1px 줄이기
* [x] 스플래시 권한 팝업 표시 시점 수정
* [x] 지도 레벨수정
